const express = require("express");
const Joi = require("joi");
const { query } = require("../lib/db");
const { requireAuth } = require("../middleware/auth");
const router = express.Router();
const schema = Joi.object({ customerId: Joi.number().integer().required(), name: Joi.string().trim().max(150).required(), projectType: Joi.string().trim().max(80).required(), siteAddress: Joi.string().trim().max(255).required(), city: Joi.string().allow("").max(100), areaSqft: Joi.number().positive().allow(null), budget: Joi.number().min(0).allow(null), startDate: Joi.date().iso().allow(null), targetDate: Joi.date().iso().allow(null), scope: Joi.string().allow("").max(4000) });
router.get("/", requireAuth, async (req, res, next) => { try { const result = await query("SELECT p.id, p.project_code AS [projectCode], p.name, p.project_type AS [projectType], p.site_address AS [siteAddress], p.city, p.area_sqft AS [areaSqft], p.budget, p.stage, p.start_date AS [startDate], p.target_date AS [targetDate], p.scope, c.id AS [customerId], c.name AS [customerName], c.phone AS [customerPhone], c.email AS [customerEmail] FROM projects p JOIN customers c ON c.id=p.customer_id ORDER BY p.created_at DESC"); res.json(result.recordset); } catch (err) { next(err); } });
router.post("/", requireAuth, async (req, res, next) => { try { const { error, value } = schema.validate(req.body); if (error) return res.status(400).json({ error: error.details[0].message }); const code = `PRJ-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`; const result = await query("INSERT INTO projects (project_code, customer_id, name, project_type, site_address, city, area_sqft, budget, start_date, target_date, scope, created_by) OUTPUT INSERTED.id VALUES (@code, @customerId, @name, @projectType, @siteAddress, @city, @areaSqft, @budget, @startDate, @targetDate, @scope, @createdBy)", { ...value, code, createdBy: req.employee.id }); const created = await query("SELECT p.id, p.project_code AS [projectCode], p.name, p.project_type AS [projectType], p.site_address AS [siteAddress], p.city, p.area_sqft AS [areaSqft], p.budget, p.stage, c.id AS [customerId], c.name AS [customerName] FROM projects p JOIN customers c ON c.id=p.customer_id WHERE p.id=@id", { id: result.recordset[0].id }); res.status(201).json(created.recordset[0]); } catch (err) { next(err); } });
module.exports = router;
