CREATE TABLE leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(255) NULL,
    city VARCHAR(100) NULL,
    address VARCHAR(255) NULL,
    project VARCHAR(150) NULL,
    message TEXT NULL,
    source VARCHAR(50) NOT NULL,
    value DECIMAL(14, 2) NULL,
    stage VARCHAR(30) NOT NULL DEFAULT 'New'
        CONSTRAINT ck_leads_stage CHECK (stage IN ('New', 'Qualified', 'Consultation', 'Proposal', 'Execution', 'Won', 'Lost')),
    owner_id INTEGER NULL REFERENCES employees(id),
    next_action_date DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
