CREATE TABLE IF NOT EXISTS quotations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no VARCHAR(40) NOT NULL UNIQUE,
    customer_id INTEGER NULL REFERENCES customers(id),
    customer_name VARCHAR(100) NOT NULL,
    project_name VARCHAR(150) NOT NULL,
    project_address VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft', 'Sent', 'Approved', 'Rejected', 'Expired')),
    valid_until DATE NULL,
    subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,
    discount DECIMAL(14,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(5,2) NOT NULL DEFAULT 18,
    tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(14,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_by INTEGER NOT NULL REFERENCES employees(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotation_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id INTEGER NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
    item_name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    quantity DECIMAL(12,2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    unit_price DECIMAL(14,2) NOT NULL,
    line_total DECIMAL(14,2) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);
