-- Add extended customer fields introduced in migration 006.
-- Each ADD COLUMN is wrapped in a DO block to safely skip if the column already exists.
DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN phone VARCHAR(30) NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN email VARCHAR(255) NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN address VARCHAR(255) NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN city VARCHAR(100) NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN company_name VARCHAR(150) NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN gstin VARCHAR(20) NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE customers ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'Active';
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(40) NOT NULL UNIQUE,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    name VARCHAR(150) NOT NULL,
    project_type VARCHAR(80) NOT NULL,
    site_address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NULL,
    area_sqft DECIMAL(12,2) NULL,
    budget DECIMAL(14,2) NULL,
    stage VARCHAR(40) NOT NULL DEFAULT 'Enquiry',
    start_date DATE NULL,
    target_date DATE NULL,
    scope TEXT NULL,
    created_by INTEGER NOT NULL REFERENCES employees(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Add project_id FK to quotations if it does not already exist.
DO $$ BEGIN
    ALTER TABLE quotations ADD COLUMN project_id INTEGER NULL REFERENCES projects(id);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
