CREATE TABLE IF NOT EXISTS project_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id),
    amount DECIMAL(14,2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_mode VARCHAR(50) NOT NULL,
    reference_no VARCHAR(100) NULL,
    notes VARCHAR(500) NULL,
    created_by INTEGER NOT NULL REFERENCES employees(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
