-- Google reviews, ingested into the CRM for moderation before any of them
-- reach the public website.
--
-- The flow is deliberately one-way and gated:
--   Google Business Profile  ->  this table (display_status = 'pending')
--                            ->  super admin approves in the CRM
--                            ->  GET /api/reviews/public serves it
--                            ->  marketing site renders it
--
-- The marketing site NEVER talks to Google. It only ever reads approved rows
-- from our own backend, so nothing appears publicly that a super admin has
-- not explicitly chosen.

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 'google' for anything synced from the Business Profile API.
    -- 'manual' for a real review a super admin transcribed by hand (used
    -- before API access is granted). Provenance is tracked rather than
    -- blurred, so it is always clear where a published quote came from.
    source VARCHAR(20) NOT NULL DEFAULT 'google'
        CONSTRAINT ck_reviews_source CHECK (source IN ('google', 'manual')),

    -- Google's own review id. Unique per source so re-syncing updates the
    -- existing row instead of duplicating it. NULL for manual entries.
    external_id VARCHAR(255) NULL,

    author_name VARCHAR(150) NOT NULL,
    author_photo_url VARCHAR(500) NULL,

    -- How the person described themselves ("Homeowner", "Business Owner").
    -- Google reviews carry no such field, so this is NULL for them; it exists
    -- for the written testimonials the site published before Google was
    -- connected, which did have one.
    author_role VARCHAR(100) NULL,

    -- Nullable on purpose. Every Google review carries a star rating, but a
    -- written testimonial does not — the older ones on this site were quotes
    -- with no score attached. Writing 5 for those would be inventing a data
    -- point the person never gave, so the column allows NULL and the website
    -- simply shows no stars when there are none. The range is still enforced
    -- whenever a rating IS present.
    rating SMALLINT NULL
        CONSTRAINT ck_reviews_rating CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    text TEXT NULL,
    review_url VARCHAR(500) NULL,
    reviewed_at TIMESTAMPTZ NULL,

    -- Moderation. Nothing is public until a super admin sets 'approved'.
    display_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CONSTRAINT ck_reviews_display_status
        CHECK (display_status IN ('pending', 'approved', 'hidden')),
    display_order INTEGER NOT NULL DEFAULT 0,
    moderated_by INTEGER NULL REFERENCES employees(id),
    moderated_at TIMESTAMPTZ NULL,

    synced_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One row per Google review. Partial index so the many manual rows (all with
-- external_id NULL) don't collide with each other under the uniqueness rule.
CREATE UNIQUE INDEX IF NOT EXISTS ux_reviews_source_external
    ON reviews (source, external_id)
    WHERE external_id IS NOT NULL;

-- The public endpoint's only query: approved rows in display order.
CREATE INDEX IF NOT EXISTS ix_reviews_public
    ON reviews (display_status, display_order, reviewed_at DESC);
