-- Money receipts — a standalone financial document acknowledging a payment
-- received from a customer (advance, milestone, final settlement). Built the
-- same way as quotations: its own table, its own numbered series, generated
-- as a PDF in the CRM with preview + download.
--
-- A receipt is a record of something that already happened, so it is kept
-- deliberately simple: no draft/sent workflow. It is either 'Active' or, if
-- it was raised in error, 'Cancelled' (kept for the audit trail rather than
-- deleted, though a hard delete is still allowed for a genuine mistake).
--
-- customer_name / project_name are denormalised on purpose: a receipt is a
-- printed document and must still read correctly if the linked customer or
-- project is later removed. The foreign keys therefore SET NULL on delete
-- rather than blocking it or cascading the receipt away.

CREATE TABLE IF NOT EXISTS money_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(40) NOT NULL UNIQUE,

    customer_id INTEGER NULL REFERENCES customers(id) ON DELETE SET NULL,
    project_id INTEGER NULL REFERENCES projects(id) ON DELETE SET NULL,
    quotation_id INTEGER NULL REFERENCES quotations(id) ON DELETE SET NULL,

    customer_name VARCHAR(100) NOT NULL,
    project_name VARCHAR(150) NULL,

    amount DECIMAL(14,2) NOT NULL
        CONSTRAINT ck_money_receipts_amount CHECK (amount > 0),
    -- Authoritative words form, computed by the API from `amount` on write.
    amount_in_words VARCHAR(400) NOT NULL,

    payment_mode VARCHAR(40) NOT NULL
        CONSTRAINT ck_money_receipts_mode
        CHECK (payment_mode IN ('Cash', 'UPI', 'Bank Transfer', 'Cheque', 'Card', 'Other')),
    -- Cheque no / UPI ref / NEFT ref, etc. Optional for cash.
    reference_no VARCHAR(80) NULL,
    received_on DATE NOT NULL,

    -- What the payment is for, e.g. "Advance against modular kitchen work".
    towards VARCHAR(500) NULL,
    notes VARCHAR(1000) NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'Active'
        CONSTRAINT ck_money_receipts_status CHECK (status IN ('Active', 'Cancelled')),

    created_by INTEGER NOT NULL REFERENCES employees(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_money_receipts_customer ON money_receipts (customer_id);
CREATE INDEX IF NOT EXISTS ix_money_receipts_project ON money_receipts (project_id);
CREATE INDEX IF NOT EXISTS ix_money_receipts_created ON money_receipts (created_at DESC);
