import React, { useEffect, useState } from "react";
import { Plus, UsersRound, Building2 } from "lucide-react";
import { api } from "../lib/api";

export default function CustomerProjectPipeline({ mode }) {
  const [customers, setCustomers] = useState([]); const [projects, setProjects] = useState([]); const [error, setError] = useState("");
  const load = () => Promise.all([api.getCustomers(), api.getProjects()]).then(([c, p]) => { setCustomers(c); setProjects(p); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, []);
  const addCustomer = async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { const saved = await api.createCustomer({ name:f.get("name"), phone:f.get("phone"), email:f.get("email"), address:f.get("address"), city:f.get("city"), companyName:f.get("company"), gstin:f.get("gstin") }); setCustomers([saved,...customers]); e.currentTarget.reset(); } catch (x) { setError(x.message); } };
  const addProject = async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { const saved = await api.createProject({ customerId:Number(f.get("customerId")), name:f.get("name"), projectType:f.get("type"), siteAddress:f.get("address"), city:f.get("city"), areaSqft:f.get("area") ? Number(f.get("area")) : null, budget:f.get("budget") ? Number(f.get("budget")) : null, startDate:f.get("start") || null, targetDate:f.get("target") || null, scope:f.get("scope") }); setProjects([saved,...projects]); e.currentTarget.reset(); } catch (x) { setError(x.message); } };
  const field = "mt-1 w-full rounded-xl border border-line-strong px-3 py-2.5 text-sm font-normal outline-none focus:border-sage-500";
  if (mode === "customers") return <><div><p className="text-[.62rem] font-bold uppercase tracking-label text-sage-600">Customer master</p><h2 className="mt-1 font-display text-3xl">Register a customer</h2><p className="mt-1 text-sm text-ink-muted">Create a permanent client record before opening a project.</p></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<form onSubmit={addCustomer} className="mt-6 grid gap-4 rounded-2xl border border-line bg-white p-5 shadow-hair md:grid-cols-3">{[["name","Customer name",true],["phone","Phone",true],["email","Email"],["company","Company / billing name"],["gstin","GSTIN"],["city","City"],["address","Address / locality"]].map(([name,label,required])=><label key={name} className={name==="address"?"md:col-span-3 text-sm font-semibold":"text-sm font-semibold"}>{label}<input name={name} required={required} className={field}/></label>)}<button className="btn-primary md:col-span-3"><Plus size={16}/> Save customer</button></form><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{customers.map(c=><article key={c.id} className="rounded-2xl border border-line bg-white p-5 shadow-hair"><UsersRound size={18} className="text-sage-600"/><h3 className="mt-4 font-display text-xl">{c.name}</h3><p className="mt-1 text-sm text-ink-muted">{c.phone} · {c.city || "City not recorded"}</p><p className="mt-3 text-xs text-ink-muted">{c.companyName || c.company_name || "Individual customer"}</p></article>)}</div></>;
  return <><div><p className="text-[.62rem] font-bold uppercase tracking-label text-sage-600">Project register</p><h2 className="mt-1 font-display text-3xl">{mode === "current" ? "Current projects" : "All projects"}</h2></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<form onSubmit={addProject} className="mt-6 grid gap-4 rounded-2xl border border-line bg-white p-5 shadow-hair md:grid-cols-3"><label className="text-sm font-semibold">Registered customer<select name="customerId" required className={field}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.phone}</option>)}</select></label><label className="text-sm font-semibold">Project name<input name="name" required className={field}/></label><label className="text-sm font-semibold">Project type<select name="type" className={field}>{["Residential interiors","Commercial interiors","Salon / retail","Office","Modular kitchen","Renovation"].map(x=><option key={x}>{x}</option>)}</select></label><label className="md:col-span-3 text-sm font-semibold">Site address<input name="address" required className={field}/></label>{[["city","City"],["area","Area (sq ft)"],["budget","Estimated budget"],["start","Start date"],["target","Target completion"]].map(([name,label])=><label key={name} className="text-sm font-semibold">{label}<input name={name} type={name==="start"||name==="target"?"date":"text"} className={field}/></label>)}<label className="md:col-span-3 text-sm font-semibold">Design scope<textarea name="scope" rows="3" className={field}/></label><button className="btn-primary md:col-span-3"><Plus size={16}/> Register project</button></form><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=><article key={p.id} className="rounded-2xl border border-line bg-white p-5 shadow-hair"><Building2 size={18} className="text-sage-600"/><p className="mt-4 text-xs font-bold text-sage-600">{p.projectCode}</p><h3 className="mt-1 font-display text-xl">{p.name}</h3><p className="mt-1 text-sm text-ink-muted">{p.customerName} · {p.projectType}</p><p className="mt-3 text-xs text-ink-muted">{p.siteAddress}</p></article>)}</div></>;
}
